export interface Pessoa{
    id: string,
    nome?: string,
    nomeSocial?: string,
    cpf?: number,
    email?: string,
    escola?: string,
    endereco?: string,
    cnpj?: string,
    cidade?: string,
    cep?: string,
    estado?: string,
    pais?: string,
    telefone?: string,
}
